control_hz: 10
DoF: 6
gripper: false

# Franka model: 'panda' 'fr3'
robot_type: "panda"

# randomize arm position on reset
randomize_ee_on_reset: false
# allows user to pause to reset reset of the environment
pause_after_reset: false

# observation space configuration
qpos: true
ee_pos: true
imgs: false
normalize: false

# pass IP if not running on NUC "localhost" if running on NUC None if running sim
ip_address: "172.16.0.1"
# specify path length if resetting after a fixed length
max_path_length: 20
# camera type to use: 'realsense' 'zed'
camera_model: "realsense"
camera_resolution: null  # (128 128) -> HxW
calibration_file: "perception/cameras/calibration/logs/aruco/most_recent_calib.json"
# Mujoco: model name
model_name: "base_franka"
on_screen_rendering: false