name: franka
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - librealsense=2.54.2.5684
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - cuda-nvcc
  - cmake
  - pybind11
  - py
  - pip
  - pip:
    - mujoco==3.0.0
    - opencv-python
    - open3d
    - dm-robotics-moma
    - gym==0.22.0
    - mujoco-python-viewer
    - hydra-core
    - wandb
