name: polymetis
channels:
  - pytorch
  - fair-robotics
  - aihabitat
  - conda-forge
  - defaults
dependencies:
  - polymetis
  - librealsense=2.54.2.5684
  - scipy=1.7.3
  - cmake
  - pybind11
  - py
  - pip
  - pip:
    - opencv-python
    - open3d
    - sophuspy
    - dm-robotics-moma
    - protobuf==3.20.1
    - gtsam
    - gym==0.22.0
    - mujoco==3.0.0
    - mujoco-python-viewer
    - hydra-core==1.3.2
    - wandb
