control_hz: 10
DoF: 6
gripper: true

# Franka model: 'panda' 'fr3'
robot_type: "panda"

# randomize arm position on reset
randomize_ee_on_reset: false
# allows user to pause to reset reset of the environment
pause_after_reset: false

# observation space configuration
qpos: true
ee_pos: true
imgs: true
normalize: false

# pass IP if not running on NUC "localhost" if running on NUC None if running sim
ip_address: null
# specify path length if resetting after a fixed length
max_path_length: 20
# camera type to use: 'realsense' 'zed'
camera_model: null
camera_resolution: null  # (128 128) -> HxW
calibration_file: "cameras/calibration/calibration_aruco_real.json"
# Mujoco: model name
model_name: "base_franka"
on_screen_rendering: false