obj_id: "cube"
joint_type: "free"
obj_pose_noise_dict:
  {
    "x": { "min": -0.05, "max": 0.05 },
    "y": { "min": -0.1, "max": 0.1 },
    "yaw": { "min": -0.76, "max": 0.76 },
  }
obs_keys: ["lowdim_ee", "lowdim_qpos", "obj_pose"]
safety_penalty: 0.
color_track: "red"
filter: false
flatten: false
