num_trajectories: -1
batch_size: 32
num_epochs: 1000

hidden_dim: 128

# checkpoint_path: "${hydra:runtime.cwd}/${checkpoint_name: ${num_trajs}}"
dataset_path: "data/pick_red_cube_synthetic/train"

image_keys: ["left_rgb"]
state_keys: ["lowdim_ee", "lowdim_qpos"]
