num_trajs: -1
batch_size: 32
num_epochs: 1000

# checkpoint_path: "${hydra:runtime.cwd}/${checkpoint_name: ${num_trajs}}"
dataset_path: "data/green_block/train"

image_keys: ["215122255213_rgb"]
state_keys: ["lowdim_ee", "lowdim_qpos"]

action_dim: 7
state_len: 15

with_state: True
