num_trajs: 10 # -1
batch_size: 4
num_epochs: 1

# checkpoint_path: "${hydra:runtime.cwd}/${checkpoint_name: ${num_trajs}}"
dataset_path: "data/pick_red_cube_synthetic/train"

pred_horizon: 16
obs_horizon: 2
action_horizon: 8
num_diffusion_iters: 100

image_keys: ["left_rgb"]
state_keys: ["lowdim_ee", "lowdim_qpos"]

action_dim: 7
state_len: 15

with_state: True
