num_trajs: -1
batch_size: 32
num_epochs: 1000

# checkpoint_path: "${hydra:runtime.cwd}/${checkpoint_name: ${num_trajs}}"
dataset_path: "data/pick_red_cube_synthetic_1k/train"

pred_horizon: 12
obs_horizon: 4
action_horizon: 8
num_diffusion_iters: 100

image_keys: ["left_rgb"]
state_keys: ["lowdim_ee", "lowdim_qpos"]

action_dim: 7
state_len: 15

with_state: True
