hydra:
  job:
    chdir: false
  
defaults:
  - log: stdout
  - env: cube
  - robot: sim_6_dof

exp_id: "pick_red_cube_synthetic_sl"

seed: 0
gpu_id: 0
episodes: 10
max_episode_length: 100
act_noise_std: 0.01