parameter_dict: {
  "inertia": {"type": "uniform", "min": -0.1, "max": 0.1, "value": null},
  "friction": {"type": "gaussian", "mean": 1.0, "std": 0.05, "value": null}
}

reward: true
delta: 0.1
normalization: 0.02

obs_noise: 0.
