# careful when adjusting friction -> too high values cause the object to penetrate the table and give huge reward signals even if not touched
parameter_dict: {
  # "surface_friction": {"type": "uniform", "min": 0.00005, "max": 0.055, "value": null},
  "friction": {"type": "uniform", "min": 0.00005, "max": 0.055, "value": null},
# "damping": {"type": "uniform", "min": 0., "max": 5., "value": null},
# "mass": {"type": "uniform", "min": 0.01, "max": 0.3, "value": null},
# "frictionloss": {"type": "uniform", "min": 0., "max": 5., "value": null},
}

reward: true
delta: 0.1
normalization: 0.02

obs_noise: 0.05
