hydra:
  job:
    chdir: false
  
defaults:
  - log: stdout

  - robot: sim_6_dof
  - env: cube
  - aug: crop_resize

exp_id: null

seed: 0
gpu_id: 0

episodes: 10
max_episode_length: 100

act_noise_std: 0.005