hydra:
  job:
    chdir: false
  
defaults:
  - log: stdout
  - robot: sim_6_dof
  - env: "cube"
  - aug: crop_resize

exp_id: null

seed: 0
gpu_id: 0

episodes: 10
# maximum timesteps to collect before auto-reset
max_episode_length: 1000
# std of action noise applied on top of input cmd
act_noise_std: 0.001

# data split \in ["train", "eval"]
split: "train"
# resume collection from traj index
start_traj: 0

language_instruction: "pick up the green cube"
