hydra:
  job:
    chdir: false
  
defaults:
  - log: stdout
  - robot: sim_6_dof
  - env: cube
  - training: diffusion_policy
  - inference: diffusion_policy

seed: 0
gpu_id: 0

exp_id: "diffusion_policy"

