hydra:
  job:
    chdir: false
  
defaults:
  - log: wandb

  - robot: real_6_dof
  - aug: crop_resize

exp_id: null

seed: 0
gpu_id: 0

n_rollouts: 10

# maximum timesteps to run before auto-reset
max_episode_length: 100

msg: "pick up the green cube"
url: "http://10.92.1.3:32820/"
minmaxlst: [[-0.01456916332244873, 0.005263835191726685], [-0.00746617466211319, 0.004066735506057739], [-0.03164529800415039, 0.019880175590515137], [-6.2823528332185, 6.282048645007373], [-0.025769426306363474, 0.011685490550377597], [-0.015799052349868337, 0.01802915374843317]]