hydra:
  job:
    chdir: false
  
defaults:
  - log: stdout

  - robot: sim_6_dof
  - env: cube
  - aug: crop_resize

  # - training: bc_policy
  # - inference: diffusion_policy

exp_id: null

seed: 0
gpu_id: 0

n_rollouts: 10

open_loop: false
open_loop_split: "eval"
# ckpt_path: "robomimic/bc_trained_models/gaussian/20240427091609/models/model_epoch_500.pth"
data_path: "/media/marius/X9 Pro/libero_90/all_libero_90/demos.hdf5"

framework: "robomimic"
ckpt_path: "/home/marius/Projects/robomimic/robomimic/logdir/tmp/diffusion/20240522131049/models/model_epoch_1000.pth"
# ckpt_path: "robomimic/bc_trained_models/gaussian_rnn_img/20240427093916/models/model_epoch_20.pth"

language_instruction: "pick up the green cube"
