n_restarts: 1
n_epochs: 10
fit_per_epoch: 1 # 3
population_size: 512
rnd_env_seed: true

algorithm:
  algo_name: cem
  elite_frac: 0.1
  keep_elite: false # true
  wmle: false

  # algo_name: reps
  eps: 5.

  # algo_name: creps
  # eps: 1.
  kappa: 0.5

distribution:
  dist: diag # cholesky
  mu_init: 0.
  sigma_init: 0.05