load_policy: false

total_timesteps: 2_000_000

fd_delta: 01
rew_normalization: 0.02

algorithm:

  buffer_size: 1_000_000

  learning_starts: 500
  train_freq: 1
  gradient_steps: 1

  ent_coef: 0.0001