name: asid
channels:
  - pytorch
  - fair-robotics
  - aihabitat
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.13.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - polymetis
  - librealsense=2.50.0
  - scipy=1.7.3
  - cmake
  - pybind11
  - py
  - pip
  - pip:
    - opencv-python
    - open3d
    - sophuspy
    - dm-robotics-moma
    - protobuf==3.20.1
    - gtsam
    - gym==0.22.0
    - mujoco==3.0.0
    - mujoco-python-viewer
    - hydra-core==1.3.2
    - wandb
    - tqdm
    - rich
    - shimmy>=0.2.1
    - moviepy
    - imageio
