obj_id: "cube"
joint_type: "free"
obj_pose_init: [0.5, 0.0, 0.02, 0., 0., 0., 1.]
obj_pose_noise_dict:
  {
    "x": { "min": -0.1, "max": 0.1 },
    "y": { "min": -0.1, "max": 0.1 },
    # "yaw": { "min": -0., "max": 0.0 },
    "yaw": { "min": 0., "max": 1.57 },
  }
obs_keys: ["lowdim_ee", "lowdim_qpos", "obj_pose"]
safety_penalty: 0.
color_track: "red"
filter: false
flatten: false
