msg: "Pick up the red block"
url: "http://10.92.1.3:32813/"
minmaxlst: [[-0.048938435, 0.032427713], [-0.016858675, 0.04141308], [-0.07068745, 0.071603075], [-0.07210768, 0.0466024], [-0.0990548, 0.079033166], [-0.07181717, 0.101365425]]