msg: "Pick up the red block"
url: "http://10.92.1.3:32812/"
minmaxlst: [[-0.046497986, 0.04100283], [-0.04833973, 0.02885204], [-0.03818984, 0.050623566], [-0.036134202, 0.02483397], [-0.064466156, 0.031492278], [-0.14267108, 0.041277315]]