msg: "Pick up the red block"
url: "http://10.92.1.4:32890/"
minmaxlst: [[-0.05896928, 0.048040226], [-0.05545263, 0.06980111], [-0.07178802, 0.07497924], [-0.07976582, 0.08366032], [-0.14934388, 0.11501943], [-0.14999823, 0.14997135]]