hydra:
  job:
    chdir: false
  
defaults:
  - asid: inertia
  - env: rod
  - robot: sim_2_dof
  - train: explore
  - log: wandb

exp_id: "explore_rod_sim"

seed: 0
gpu_id: 0
num_workers: 16
num_workers_eval: 8