hydra:
  job:
    chdir: false
  
defaults:
  - asid: inertia
  - env: rod
  - robot: sim_2_dof
  - train: explore
  - log: stdout

exp_id: "inertia"

seed: 0
gpu_id: 0
num_workers: 64
num_workers_eval: 8