hydra:
  job:
    chdir: false
  
defaults:
  - asid: inertia # _friction
  - env: rod
  - robot: sim_2_dof
  - train: sysid
  - log: stdout

exp_id: "inertia_second"

seed: 0
gpu_id: 0
num_workers: 8